-----BEGIN EC PRIVATE KEY-----
MHcCAQEEICgdL+GdcWC+cc8IGPeJxZrtkt+CPlM1QIIe+KkH0jEHoAoGCCqGSM49
AwEHoUQDQgAE2g5jLl9T7Zm6OI6rF7VM2l2UyH/ddOzKDfLL4Y7qUyQpq/ATBQXT
eDIl9YKAoSq/3ALHNrghQSF+SwC2/Tpk6w==
-----END EC PRIVATE KEY-----
